### ISSUE TITLE
Missing other states of Malaysia

### ISSUE THREAD

**Issue by TheStrangerDoctor** [rubyconfmy/malaysia#10]
This is a very good project overall. However you named the repository as "Malaysia" and I can only see abundant information for "Kuala Lumpur". 

The last time this repo is updated was in 2016. Would you consider updating this repository? 

For me personally, I would not mind helping out for some of the states. Let me know what do you think. Thank you!

**Comment by jimmynguyc** [comment]
Hey @TheStrangerDoctor 

This repo's original intent was to hopefully provide some useful information for the overseas attendees of Rubyconf MY in 2016, hence the focus on KL, and the complete lack of update since 😛. 

Unfortunately there's no plans to host Ruby conferences in KL/Malaysia for the foreseeable future, so I think it might not serve much purpose, at least in this context, to update this repo.

That being said, if you can think of a better place to put this info feel free to fork / copy-pasta it somewhere that would be of help to someone 😄
